app = 'family-tree-neo4j'
primary_region = 'dfw'
kill_signal = 'SIGTERM'

[build]
  image = 'neo4j:5.15-community'

[env]
  NEO4J_AUTH = 'neo4j/familytree123'
  NEO4J_PLUGINS = '["apoc"]'
  NEO4J_dbms_security_procedures_unrestricted = 'apoc.*'

[http_service]
  internal_port = 7474
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[services]]
  protocol = 'tcp'
  internal_port = 7687

  [[services.ports]]
    port = 7687

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = 'neo4j_data'
  destination = '/data'
